quarkus.application.name=tracing-test-shell
quarkus.http.port=8080
quarkus.http.root-path=/api/v1/central
quarkus.http.access-log.enabled=true

quarkus.container-image.image=quarkus-tracing-test:latest