services:
  app:
    image: quarkus-tracing-test:latest
    ports:
      - "8080:8080"
    volumes:
      - ./dd-java-agent-1.60.3.jar:/dd-java-agent-1.60.3.jar
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/dd-java-agent-1.60.3.jar"
      DD_SERVICE: tracing-test
      DD_ENV: local
      DD_AGENT_HOST: host.docker.internal
      DD_TRACE_DEBUG: true
